### ISSUE TITLE
Building v3.3.0.10 on Ubuntu 20.10

### ISSUE THREAD

**Issue by adamdray** [TinyMUSH/TinyMUSH#10]
Tried backing up to the last tagged version, v3.3.0.10...

./configure CFLAGS=-w --enable-module-comsys=no --enable-module-mail=no
make install

`
api.c: In function ‘register_dbtype’:
api.c:152:9: error: incompatible types when assigning to type ‘DBData’ from typ’
  152 |  data = db_get(key, DBTYPE_MODULETYPE);
      |         ^~~~~~
make[3]: *** [Makefile:691: api.o] Error 1
`

**Comment by EddyBeaupre** [comment]
Install libgdbm-dev

And keep in mind it's still alpha, i try to make sure it at least compile on a tag, but there's absolutly no waranty that it work at all at this stage .

The issues you've noticed earlier are related to the rework of the memory management i'm doing.

And i can tell you right now that it has many bugs and is prone to crash. I plan to stabilize things once i've finished the rework of the memory management.


Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : adamdray <notifications@github.com>
Date : 20-12-14 17 h 37 (GMT-05:00)
À : TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [TinyMUSH/TinyMUSH] Building v3.3.0.10 on Ubuntu 20.10 (#10)


Tried backing up to the last tagged version.

`

./configure CFLAGS=-w --enable-module-comsys=no --enable-module-mail=no
make install

api.c: In function ‘register_dbtype’:
api.c:152:9: error: incompatible types when assigning to type ‘DBData’ from typ’
152 | data = db_get(key, DBTYPE_MODULETYPE);
| ^~~~~~
make[3]: *** [Makefile:691: api.o] Error 1
`

**Comment by adamdray** [comment]
libgdbm-dev was already installed. That's not the issue.  

Is 3.3.0.10 alpha or beta? I can't remember the versioning scheme? Is all of 3.3.x alpha?

**Comment by adamdray** [comment]
I can back up to an older version. Should I be building 3.2?

**Comment by EddyBeaupre** [comment]
3.3 is alpha yes.



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : adamdray <notifications@github.com>
Date : 20-12-15 15 h 50 (GMT-05:00)
À : TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com>
Cc : Eddy Beaupré <eddy@beaupre.biz>, Comment <comment@noreply.github.com>
Objet : Re: [TinyMUSH/TinyMUSH] Building v3.3.0.10 on Ubuntu 20.10 (#10)


libgdbm-dev was already installed. That's not the issue.

Is 3.3.0.10 alpha or beta? I can't remember the versioning scheme? Is all of 3.3.x alpha?

**Comment by EddyBeaupre** [comment]
Please try now. It should work.

See the updated readme.md for build instructions.
