### ISSUE TITLE
Boolean 0

### ISSUE THREAD

**Issue by adamdray** [TinyMUSH/TinyMUSH#11]
**It seems that 0 is no longer Boolean false.** (Unless there was a change in Boolean that isn't represented in the help file.)

INCORRECT BEHAVIOR:
think t(0)
    1

**Per "help ifelse()":**

say [ifelse(1,one)] - [ifelse(0,zero)]
    You say, "one - zero"
    
CORRECT BEHAVIOR:
think t(0)
    0

**Per "help ifelse()":**

say [ifelse(1,one)] - [ifelse(0,zero)]
    You say, "one - "

**Comment by belisariussmith** [comment]
There is the option to switch over to the boolean MUX-style in funmisc.c which should make your code work as intended.Yours Truly,Belisarius
-------- Original message --------From: adamdray <notifications@github.com> Date: 3/9/21  1:26 PM  (GMT-06:00) To: TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [TinyMUSH/TinyMUSH] Boolean 0 (#11) 
It seems that 0 is no longer Boolean false. (Unless there was a change in Boolean that isn't represented in the help file.)
INCORRECT BEHAVIOR:
think t(0)
1
Per "help ifelse()":
say [ifelse(1,one)] - [ifelse(0,zero)]
You say, "one - zero"
CORRECT BEHAVIOR:
think t(0)
0
Per "help ifelse()":
say [ifelse(1,one)] - [ifelse(0,zero)]
You say, "one - "

**Comment by adamdray** [comment]
If the new behavior is 0 = false, then the help files do not match. See "help ifelse" and "help boolean" for example.

I'll try setting booleans_oldstyle to see if that helps.

**Comment by belisariussmith** [comment]
Hopefully that fixes it. Out of curiosity, what compiler and version are you using? (gcc 10.2?)

**Comment by adamdray** [comment]
No good.

VERSION
TinyMUSH version 3.3, Alpha 12 [2020-12-29]

@admin booleans_oldstyle = yes     

think config(booleans_oldstyle)
1

think t(0)
1

think ifelse(0, true, false)
true

**Comment by adamdray** [comment]
> Hopefully that fixes it. Out of curiosity, what compiler and version are you using? (gcc 10.2?)

-bash-3.2$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by belisariussmith** [comment]
I wonder if iftrue and iffalse suffer from the same problem. 

Apparently the CONVERTING documentation says to use nonzero() instead of ifelse()

**Comment by adamdray** [comment]
They have the same incorrect behavior.

think iftrue(0,true,false)
> true

think iffalse(0,true,false)
> false

**Comment by adamdray** [comment]
It's this bit in fnhelper.c around line 728:

```
726         if (is_integer(temp2))
727         {
728                 return strtoll(temp2, (char **)NULL, 10) >= 0 ? true : false;
729         }       
```

It doesn't honor the `mushconf.bools_oldstyle` parameter, which would force it to use >0 instead of >=0.

**Comment by belisariussmith** [comment]
_say [ifelse(1,one)] - [ifelse(0,zero)]_
You say "one - zero"
_say [ifelse(1,one)] - [ifelse(0,zero)]_
**You say "one - zero"**

The stock code works correctly (as seen above) on my fresh build. Which is why this probably hasn't been caught before. It seems its due to the C99 implementation being slightly different that with GCC

**Comment by belisariussmith** [comment]
This will ultimately need some modification to the configure/autogen to check for how stdbool works with clang. Although whats strange is that I see that the check is being done in **configure** - so I'm confused as to why this isn't working on your build. It must not be corrected as it should, unfortunately I don't have much experience with configure scripts.

**Comment by adamdray** [comment]
It just needs this:

```
-bash-3.2$ git diff master:src/fnhelper.c src/fnhelper.c
diff --git a/src/fnhelper.c b/src/fnhelper.c
index 560dbcd..dc2df74 100644
--- a/src/fnhelper.c
+++ b/src/fnhelper.c
@@ -725,7 +725,14 @@ bool xlate(char *arg)
 
        if (is_integer(temp2))
        {
-               return strtoll(temp2, (char **)NULL, 10) >= 0 ? true : false;
+               if (mushconf.bools_oldstyle)
+               {
+                       return strtoll(temp2, (char **)NULL, 10) > 0 ? true : false;
+               }
+               else
+               {
+                       return strtoll(temp2, (char **)NULL, 10) >= 0 ? true : false;
+               }
        }
 
        return true;
```

**Comment by adamdray** [comment]
Though I feel like the whole thing would be more elegant with something like

```
int threshhold = mushconf.bools_oldstyle ? 1 : 0;

return strtoll(temp2, (char **)NULL, 10) >= threshhold ? true : false;

**Comment by adamdray** [comment]
Oops. There's still a bug here, so I'll let a dev close it when it's handled.

**Comment by EddyBeaupre** [comment]
Feel free to subit patch, i'm currently working on rejoint the ansi/xterm handicapés from scratch so it can handle 24 bit colors. And since i'm the only dev still actively working on TinuMUSH, things don't go as fast as i would like.

There's alot of staff that configure check that isn't currently implemented in the code. And it's on the todo list.

Keep in mind that some part of the code is still from the original 1989 release. Ternary operator wasn't in the C standard yet... :)

**Comment by adamdray** [comment]
I left a patch up there in the comments. You mean submit one through git, eh?

**Comment by EddyBeaupre** [comment]
Yep!



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : adamdray ***@***.***>
Date : 21-03-10 17 h 52 (GMT-05:00)
À : TinyMUSH/TinyMUSH ***@***.***>
Cc : Eddy Beaupré ***@***.***>, Comment ***@***.***>
Objet : Re: [TinyMUSH/TinyMUSH] Boolean 0 (#11)


I left a patch up there in the comments. You mean submit one through git, eh?
