### ISSUE TITLE
dbsql/pgsql fails make

### ISSUE THREAD

**Issue by ericdaltman** [TinyMUSH/TinyMUSH#14]
Trying to build TinyMUSH 3.3 on a beefy server with a very fast internet connection, with some more modern and tuned up options.

Configure string is:
`./configure --enable-module-dbsql --with-module-dbsql=pgsql --with-pgsql-libs --with-pgsql-includes --disable-disk-based --with-env-vars=32 --with-max-iter=2048 --with-max-delim=256`

Then during 'make --debug=j install':

```
...
make[4]: Entering directory '/opt/GarouMUSH/TinyMUSH-3.3/src/libltdl'
Putting child 0x7fffbe8e7d90 (config.h) PID 17532 on the chain.
Live child 0x7fffbe8e7d90 (config.h) PID 17532
Reaping winning child 0x7fffbe8e7d90 PID 17532
Live child 0x7fffbe8e7d90 (config.h) PID 17533
Reaping winning child 0x7fffbe8e7d90 PID 17533
Removing child 0x7fffbe8e7d90 PID 17533 from chain.
make[4]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src/libltdl'
Reaping winning child 0x7fffbb571800 PID 17531
Removing child 0x7fffbb571800 PID 17531 from chain.
make[3]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src/libltdl'
Making all in modules/comsys/
make[3]: Entering directory '/opt/GarouMUSH/TinyMUSH-3.3/src/modules/comsys'
depbase=`echo comsys.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../src  -I../../../src/libltdl   -g -O2 -MT comsys.lo -MD -MP -MF $depbase.Tpo -c -o comsys.lo comsys.c &&\
mv -f $depbase.Tpo $depbase.Plo
Putting child 0x7fffdcf41470 (comsys.lo) PID 17536 on the chain.
Live child 0x7fffdcf41470 (comsys.lo) PID 17536
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../src -I../../../src/libltdl -g -O2 -MT comsys.lo -MD -MP -MF .deps/comsys.Tpo -c comsys.c  -fPIC -DPIC -o .libs/comsys.o
In file included from comsys.c:16:
../../../src/tinymushapi.h:510:2: error: unknown type name ‘Obj’
  510 |  Obj attrtext; /*!< Array of attribute text */
      |  ^~~
Reaping losing child 0x7fffdcf41470 PID 17536
make[3]: *** [Makefile:478: comsys.lo] Error 1
Removing child 0x7fffdcf41470 PID 17536 from chain.
make[3]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src/modules/comsys'
Reaping losing child 0x7fffee1a4210 PID 17522
make[2]: *** [Makefile:750: all-recursive] Error 1
Removing child 0x7fffee1a4210 PID 17522 from chain.
make[2]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src'
Reaping losing child 0x7ffff6c50c30 PID 17521
make[1]: *** [Makefile:517: all] Error 2
Removing child 0x7ffff6c50c30 PID 17521 from chain.
make[1]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src'
Reaping losing child 0x7fffe9a6a300 PID 17506
make: *** [Makefile:437: all-recursive] Error 1
Removing child 0x7fffe9a6a300 PID 17506 from chain.
```

**Comment by EddyBeaupre** [comment]
None of the SQL drivers work for now. It's in the TODO list.

Keep in mind it's still in alpha...

No ETA on when it will work again.



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : ericdaltman ***@***.***>
Date : 21-07-28 11 h 02 (GMT-05:00)
À : TinyMUSH/TinyMUSH ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [TinyMUSH/TinyMUSH] dbsql/pgsql fails make (#14)


Trying to build TinyMUSH 3.3 on a beefy server with a very fast internet connection, with some more modern and tuned up options.

Configure string is:
./configure --enable-module-dbsql --with-module-dbsql=pgsql --with-pgsql-libs --with-pgsql-includes --disable-disk-based --with-env-vars=32 --with-max-iter=2048 --with-max-delim=256

Then during 'make --debug=j install':

...

make[4]: Entering directory '/opt/GarouMUSH/TinyMUSH-3.3/src/libltdl'

Putting child 0x7fffbe8e7d90 (config.h) PID 17532 on the chain.

Live child 0x7fffbe8e7d90 (config.h) PID 17532

Reaping winning child 0x7fffbe8e7d90 PID 17532

Live child 0x7fffbe8e7d90 (config.h) PID 17533

Reaping winning child 0x7fffbe8e7d90 PID 17533

Removing child 0x7fffbe8e7d90 PID 17533 from chain.

make[4]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src/libltdl'

Reaping winning child 0x7fffbb571800 PID 17531

Removing child 0x7fffbb571800 PID 17531 from chain.

make[3]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src/libltdl'

Making all in modules/comsys/

make[3]: Entering directory '/opt/GarouMUSH/TinyMUSH-3.3/src/modules/comsys'

depbase=`echo comsys.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\

/bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../src  -I../../../src/libltdl   -g -O2 -MT comsys.lo -MD -MP -MF $depbase.Tpo -c -o comsys.lo comsys.c &&\

mv -f $depbase.Tpo $depbase.Plo

Putting child 0x7fffdcf41470 (comsys.lo) PID 17536 on the chain.

Live child 0x7fffdcf41470 (comsys.lo) PID 17536

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../src -I../../../src/libltdl -g -O2 -MT comsys.lo -MD -MP -MF .deps/comsys.Tpo -c comsys.c  -fPIC -DPIC -o .libs/comsys.o

In file included from comsys.c:16:

../../../src/tinymushapi.h:510:2: error: unknown type name ‘Obj’

  510 |  Obj attrtext; /*!< Array of attribute text */

      |  ^~~

Reaping losing child 0x7fffdcf41470 PID 17536

make[3]: *** [Makefile:478: comsys.lo] Error 1

Removing child 0x7fffdcf41470 PID 17536 from chain.

make[3]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src/modules/comsys'

Reaping losing child 0x7fffee1a4210 PID 17522

make[2]: *** [Makefile:750: all-recursive] Error 1

Removing child 0x7fffee1a4210 PID 17522 from chain.

make[2]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src'

Reaping losing child 0x7ffff6c50c30 PID 17521

make[1]: *** [Makefile:517: all] Error 2

Removing child 0x7ffff6c50c30 PID 17521 from chain.

make[1]: Leaving directory '/opt/GarouMUSH/TinyMUSH-3.3/src'

Reaping losing child 0x7fffe9a6a300 PID 17506

make: *** [Makefile:437: all-recursive] Error 1

Removing child 0x7fffe9a6a300 PID 17506 from chain.

**Comment by EddyBeaupre** [comment]
In the TODO list for a futur alpha release...

**Comment by ericdaltman** [comment]
Figured that might be the case, just reporting 'em as I see 'em.

Thank you!
