### ISSUE TITLE
Memory issues?

### ISSUE THREAD

**Issue by psc943** [TinyMUSH/TinyMUSH#3]
Strange memory usage by TM3.3:
`
--------------------------
Initial startup, empty DB:
--------------------------

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
darren    5983  0.0  0.2  20848  2996 ?        Ss   16:54   0:00 bin/netmush

-----------------------------------------------------
After @digging #2 and @pcreating a CodeWiz character:
-----------------------------------------------------

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
darren    5983  0.0  0.9  42260  9468 ?        Ss   16:54   0:00 bin/netmush

---------------------------------------------------------------
After creating 6 more objects (#3..#8), still no vattrs in use:
---------------------------------------------------------------

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
darren    5983  0.0  3.0  60100 30864 ?        Ss   16:54   0:00 bin/netmush

-------------------------------------
After installing Myrddin's BBS 4.0,6:
-------------------------------------

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
darren    5983  0.0  6.2  97776 63780 ?        Ss   16:54   0:00 bin/netmush

------------------------
Which did not even work:
------------------------

==============================================================================
       Group Name                    Last Post      # of messages
------------------------------------------------------------------------------
[iter(u(

----------------
After a restart:
----------------

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
darren    5983  0.0  0.4  20856  4308 ?        Ss   16:54   0:00 /home/darren/TinyMUSH/game/bin/netmush /home/darren/Tin

----------------------------------------------------
After typing a few random commands (look, who, etc):
----------------------------------------------------
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
darren    5983  0.0  1.3  57812 13600 ?        Ss   16:54   0:00 /home/darren/TinyMUSH/game/bin/netmush /home/darren/Tin

This was on Ubuntu 14.0.4 (X86_64) with GCC 4.8.4
`

**Comment by EddyBeaupre** [comment]
Memory management is being rebuild from the ground. Some of theses bugs have been fixed, most (hopefully) should be resolved in V3.3.0.12 when the new memory management will be fully implemented.
