### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jaybird1905** [TinyMUSH/TinyMUSH#4]
When running through the install on my Mac, I hit this snag running ./Build 

configure: creating ./config.status
config.status: creating Makefile.inc

gcc   -g  -I./gdbm-1.8.3 -c unsplit.c
In file included from unsplit.c:5:
./autoconf.h:481:20: error: expected parameter declarator
extern char     *VDECL(sprintf, (char *, const char *, ...));
                       ^
./autoconf.h:481:20: error: expected ')'
./autoconf.h:481:20: note: to match this '('
./autoconf.h:481:20: error: conflicting types for '__builtin___sprintf_chk'
extern char     *VDECL(sprintf, (char *, const char *, ...));
                       ^
./autoconf.h:481:20: note: '__builtin___sprintf_chk' is a builtin with type 'int (char *, int, unsigned long, const char *, ...)'
3 errors generated.
make: *** [unsplit.o] Error 1

**Comment by EddyBeaupre** [comment]
Fixed in 3.3.0.10.
