### ISSUE TITLE
Build issue on MacOS

### ISSUE THREAD

**Issue by adamdray** [TinyMUSH/TinyMUSH#7]
I run into immediate build issues on MacOS. It was failing on Catalina and now it's failing on Big Sur. I have xtools and such updated.

```
MacBook-Pro:gdbm-1.8.0 Adam1$ ./configure --enable-shared=no --enable-static=yes

configure:536: checking for gcc
configure:613: checking whether the C compiler (gcc  ) works
configure:627: gcc -o conftest    conftest.c  1>&5
**ld: library not found for -lSystem**
collect2: error: ld returned 1 exit status
configure: failed program was:
#line 623 "configure"
#include "confdefs.h"
main(){return(0);}
```

Also:

```
MacBook-Pro:Sandbox Adam1$ ./Build 

Building TinyMUSH 3.1...

***** Configuring GNU DBM...

loading cache ./config.cache
checking for gcc... (cached) gcc
checking whether the C compiler (gcc  ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.

***** Building GNU DBM...

make: Nothing to be done for `all'.

***** Configuring the server...
loading cache ./config.cache
checking whether to build with SQL support... no
checking for location of SQL header files... none
checking for location of SQL library files... none
checking whether to enable disk-based database... yes
checking whether to enable port concentrator... no
checking for which version of malloc to use... sys
checking whether to build with Pueblo support... yes
checking whether to use floating-point math... yes
checking whether to enable command lag detection... yes
checking whether to enable per-object time usage tracking... yes
checking whether to enable cpu time checking... no
checking whether to enable malloc-wrapper macros... no
checking how many global registers to use... 36
checking for modules to enable... comsys,mail
checking for gcc... gcc
**checking whether the C compiler (gcc  ) works... no**
configure: error: installation or configuration problem: C compiler cannot create executables.
***** Building server using default config...

gcc   -g -O  -c unsplit.c
In file included from unsplit.c:5:0:
autoconf.h:291:20: fatal error: stdlib.h: No such file or directory
compilation terminated.
make: *** [unsplit.o] Error 1

Done.
```

config.log:
```
configure:1141: checking whether the C compiler (gcc  ) works
configure:1157: gcc -o conftest    conftest.c  1>&5
**ld: library not found for -lSystem**
collect2: error: ld returned 1 exit status
configure: failed program was:

#line 1152 "configure"
#include "confdefs.h"

main(){return(0);}
```

**Comment by EddyBeaupre** [comment]
Try this:

CC=clang ./configure <wathever options you need>

MacOS doesn't use GCC. It's in the todo list of the first beta release. Since it's still early in alpha, the only thing that should work out of the box without having to fiddle with tweaks and manual patch is Ubuntu 18.04 and up...

**Comment by adamdray** [comment]
That helped a lot. Getting closer.

New issue:

```
In file included from alloc.c:27:
In file included from ./externs.h:13:
./prototypes.h:1:1: error: expected external declaration
-e /* prototypes.h : functioons prototypes */
^
./prototypes.h:1:2: error: unknown type name 'e'
-e /* prototypes.h : functioons prototypes */
 ^
./prototypes.h:7:1: error: expected identifier or '('
-e #include "copyright.h"
```

What causes all the -e's in the source? Is there a missing #define or something?

**Comment by EddyBeaupre** [comment]
Do you have cproto installed? prototype.h is generated by that utility while it's in alpha.



Envoyé depuis mon appareil Galaxy


-------- Message d'origine --------
De : adamdray <notifications@github.com>
Date : 20-12-07 20 h 54 (GMT-05:00)
À : TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com>
Cc : Eddy Beaupré <eddy@beaupre.biz>, Assign <assign@noreply.github.com>
Objet : Re: [TinyMUSH/TinyMUSH] Build issue on MacOS (#7)


That helped a lot. Getting closer.

New issue:

In file included from alloc.c:27:
In file included from ./externs.h:13:
./prototypes.h:1:1: error: expected external declaration
-e /* prototypes.h : functioons prototypes */
^
./prototypes.h:1:2: error: unknown type name 'e'
-e /* prototypes.h : functioons prototypes */
 ^
./prototypes.h:7:1: error: expected identifier or '('
-e #include "copyright.h"


What causes all the -e's in the source? Is there a missing #define or something?

**Comment by adamdray** [comment]
Yeah, cproto is installed and up-to-date. Reinstalled to be sure.

MacBook-Pro:src Adam1$ cproto -V

4.7q

**Comment by EddyBeaupre** [comment]
Probably because of clang. cproto probably doesn't find or like the c preprocessor. I don't have a Mac to investigate. FreeBSD is probably having the same issue so i could probably troubleshoot that way.

I'm adding that to the todo list... no eta for now.



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : adamdray <notifications@github.com>
Date : 20-12-08 14 h 47 (GMT-05:00)
À : TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com>
Cc : Eddy Beaupré <eddy@beaupre.biz>, Assign <assign@noreply.github.com>
Objet : Re: [TinyMUSH/TinyMUSH] Build issue on MacOS (#7)


Yeah, cproto is installed and up-to-date. Reinstalled to be sure.

MacBook-Pro:src Adam1$ cproto -V

4.7q

**Comment by EddyBeaupre** [comment]
Please try now. It should work in Ubuntu/Debian.

See the updated readme.md for build instructions.

You can also try in MacOS, maybe it's also fixed, You need alll the autotools (brew install autoconf automake libtool), cproto, libpcre3-dev and libgdbm-dev.

**Comment by EddyBeaupre** [comment]
Fixed for Mac OSX.

    TinyMUSH version 3.3, Alpha 11 (2020-11-03)
    -------------------------------------------
    
         Build date: Sun, 27 Dec 2020 13:29:39 -0800
     Build platform: Darwin 20.2.0 x86_64
    Configure Flags: --enable-ltdl-convenience
     Compiler Flags: gcc -DHAVE_CONFIG_H -I. -I../src/libltdl -g -O2
       Linker Flags: /bin/sh ../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I../src/libltdl -g -O2
    
    Module comsys
    -------------
    
            Version: 3.3, Alpha 11 (2020-11-03)
             Author: TinyMUSH Development Team
              Email: tinymush@googlegroups.com
            Website: https://github.com/TinyMUSH
          Copyright: Copyright (C) 2012 TinyMUSH development team.
        Description: Communication system for TinyMUSH
    
    Module mail
    -----------
    
            Version: 3.3, Alpha 11 (2020-11-03)
             Author: TinyMUSH Development Team
              Email: tinymush@googlegroups.com
            Website: https://github.com/TinyMUSH
          Copyright: Copyright (C) 2012 TinyMUSH development team.
        Description: Mail system for TinyMUSH
