### ISSUE TITLE
Building on Ubuntu 20.10

### ISSUE THREAD

**Issue by adamdray** [TinyMUSH/TinyMUSH#9]
You said that it should build out of the box on Ubuntu 18+ so I grabbed a new linode and set up all the dev tools, PCRE, GDBM, etc.

I'm getting a successful "./configure CFLAGS=-w" but it's failing to "make install" with this error:

`
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../src -I../../../src/libltdo
comsys.c:59:31: error: ‘cf_string’ undeclared here (not in a function)
   59 |     {(char *)"guests_calias", cf_string, CA_STATIC, CA_PUBLIC, (int *)&,
      |                               ^~~~~~~~~
make[3]: *** [Makefile:475: comsys.lo] Error 1
`

Looks like it doesn't see src/conf.c's functions.

If I turn off modules and configure with "./configure CFLAGS=-w --enable-module-comsys=no --enable-module-mail=no" I still get an error:

`
gcc -DHAVE_CONFIG_H -I.  -I../src/libltdl   -w -MT alloc.o -MD -MP -MF $depbase\
mv -f $depbase.Tpo $depbase.Po
alloc.c:218:11: error: conflicting types for ‘__xfind’
  218 | MEMTRACK *__xfind(void *ptr)
      |           ^~~~~~~
alloc.c:170:12: note: previous implicit declaration of ‘__xfind’ was here
  170 |     mtrk = __xfind(ptr);
      |            ^~~~~~~
make[3]: *** [Makefile:691: alloc.o] Error 1
`

**Comment by EddyBeaupre** [comment]
Please try now. It should work.

See the updated readme.md for build instructions.
